### ISSUE TITLE
Missing npm package for the project

### ISSUE THREAD

**Issue by ThePeach** [Comcast/patternlab-edition-node-webpack#1]
First of all, many thanks for releasing the webpack edition of PL as OSS! very much appreciated.

I was expecting to find the project in the npm registry as well, so instead of having to clone the project I can add it as a dependency of a project.
This is one of the installation alternatives suggested by the [Gulp Edition of Patternlab](https://github.com/pattern-lab/edition-node-gulp#install-the-gulp-edition-of-pattern-lab-node-as-a-dependency).

Thanks

**Comment by mbulfair** [comment]
Thanks for suggestion, this is a great thing to do, I will certainly follow along with the other editions

**Comment by mbulfair** [comment]
@ThePeach [NPM - Edition Node Webpack](https://www.npmjs.com/package/edition-node-webpack) I'll update the documentation in a following release.
