### ISSUE TITLE
Explain extending the base setup a little further

### ISSUE THREAD

**Issue by moda-schneij** [Comcast/patternlab-edition-node-webpack#10]
## I found the following issue:

Not exactly an issue, but I'm unclear on extending the base, particularly whether all dependencies in the wrapper package.json must be deps and not devDeps.

### Recommendations on Solutions:

Add a note to the readme, explaining. Thanks

**Comment by mbulfair** [comment]
Can you elaborate what exactly you are trying to extend?

**Comment by Josh68** [comment]
For example, adding loaders like sass-loader, postcss-loader, etc, or a plugin like clean-webpack or extract-text. As is often the case, it may just not be clear to me what's a dev dependency and what needs to be included in the bundle. I think the loaders need to be in dependencies, but what about typical plugins? Thanks

**Comment by Josh68** [comment]
I just realized there actually is a dev dependencies section in the package.json for the devServer, so really this is just me figuring out what goes where. Please close this. Sorry about that.

**Comment by mbulfair** [comment]
No worries, if I can help again, please don't hesitate to reach out.

**Comment by Josh68** [comment]
Thanks for the help. Progressing with my setup.
