### ISSUE TITLE
Documentation on adding a starterkit needs amending

### ISSUE THREAD

**Issue by moda-schneij** [Comcast/patternlab-edition-node-webpack#11]
## I found the following issue:

The documentation on adding a starter kit seems a little off. 

I've added the [starterkit-mustache-demo](https://www.npmjs.com/package/starterkit-mustache-demo), but that's inserted scripts in my source/js file that aren't being picked up during development. 

I think I'll need to expose them as modules and either append to my entry js or expose as new entries. Or figure out how to update the copy plugin to catch non-modular JS and copy from source to public.

This may be an issue of using non-webpack starterkits with the webpack wrapper.

In any case, the documentation says

> To install a specific StarterKit from GitHub type:
> 
> ```npm run add [starterkit-vendor/starterkit-name]```
> 
> ```npm run patternlab:loadstarterkit --kit=[starterkit-name]```

But there is no `add` script in `package.json`

### Recommendations on Solutions:

Amend documentation to explain how to do this, and/or how to deal with problems with available starter kits. Thanks.

**Comment by mbulfair** [comment]
Yup you are correct, it's a typo  the first line should be `npm install [starterkit-name]` then the second. I will get that corrected.

**Comment by Josh68** [comment]
Thanks. Still working out how to customize this wrapper in certain ways (like adding the html-webpack-plugin to my webpack.app.js, as it seems to blow away the patternlab iframe wrapper), but thanks for making it. I hope it eventually becomes a new standard approach for the node version.

**Comment by mbulfair** [comment]
Have you seen this: https://github.com/Comcast/patternlab-edition-node-webpack#setting-the-webpack-merge-options there's a link there to a readme that goes over the webpack merge options.

**Comment by Josh68** [comment]
Yes, I did read that and the merge docs for webpack. Just experimenting to see how things work. Patternlab adds a layer of indirection (or that's how I'm seeing it) with the wrapper around the iframe that contains your actual bundles. That said, I have gotten some customizations to work, and merging options seem sensible.
