### ISSUE TITLE
Upgrade to use patternlab core 3.x

### ISSUE THREAD

**Issue by mbulfair** [Comcast/patternlab-edition-node-webpack#13]
Upgrade the edition to support https://github.com/pattern-lab/patternlab-node/releases latest release. 

Which includes pattern-lab/patternlab-node#745

**Comment by bmuenzenmeyer** [comment]
Should also include https://github.com/pattern-lab/patternlab-node/issues/745

**Comment by renestalder** [comment]
Wouldn't it be better to separate the upgrade to Webpack 4 to a separate task? Sure these are both breaking changes but still, in case one or the other gets stuck, you're still open to create a release independently.

Also, I think I could more easily contribute to the Webpack part if needed, but not to the patternlab core one.

**Comment by mbulfair** [comment]
@renestalder Thank you, I've split it up, #16 is dedicated to that work. This is a great suggestion thank you. The more contributors the better.

**Comment by mbulfair** [comment]
Thank you @Josh68  I will take a look as soon as I can.

**Comment by Josh68** [comment]
FWIW, I think my fork is not a good reference. I've been re-reading the upgrade docs for PL v3, and I'm now trying to wrap my head around what Webpack will handle, and how, and it's substantially different with v3 than with v2. 

My own goal is to have the ability to use loaders, primarily for SASS/Postcss, and plugins. but with PL core handling file copying and potentially dev serving and watching, I've kind of lost a grasp on how to configure Webpack to do a more minimal set of tasks, at the right time and in the right order.

Would it make sense to define goals for a v3 conversion?

**Comment by mbulfair** [comment]
Let's connect on gitter @Josh68

**Comment by mbulfair** [comment]
Now with upgrading of Webpack to version 4, this prepares this edition to work better with the core 3.x release.
