### ISSUE TITLE
Yarn dependency not documented

### ISSUE THREAD

**Issue by Josh68** [Comcast/patternlab-edition-node-webpack#15]
## I found the following issue:

Yarn is required to run, as the `package.json` is setup right now

### Recommendations on Solutions:

Document the need to install Yarn or change the way the serve task is executed. I'm happy to add to documentation if you want to leave the task as is.

**Comment by mbulfair** [comment]
Hello @Josh68 Yarn was removed, looks like I forgot to remove the `start` step. `npm run patternlab:serve` should work. Thank you and I will make sure to make the update.

**Comment by Josh68** [comment]
Thanks for the update
