### ISSUE TITLE
Not working with nunjucks

### ISSUE THREAD

**Issue by ivandoric** [Comcast/patternlab-edition-node-webpack#19]
## I found the following issue:

Tried to use this edition with https://github.com/pattern-lab/patternengine-node-nunjucks but only thing I get from the pattern is `[Object promise]` instead of the actual html of the pattern. And the pattern isn't even using nunjucks, the code is just something like `<button>Button</button>` but the file has `.njk` extension. If I change it to mustache it works fine. 

Also just to mention when running `patternlab:serve` i get the message that both mustache and nunjucks are ready to go. So I guess that the engine is ok.

Also I used nunjucks some time ago with Gulp edition and everything worked fine. 

Haven't tested this with other engines, so maybe those have problems also.

Anyway let me know if you need more info about this.

**Comment by Josh68** [comment]
Not sure, but I don't know if any of the @pattern-lab scoped packages will work with this edition until it's upgraded to v3. For example, I use [patternengine-node-handlebars v1.0.3](https://www.npmjs.com/package/patternengine-node-handlebars) successfully, not [v2.0.0-alpha.2](https://www.npmjs.com/package/@pattern-lab/patternengine-node-handlebars). For Nunjucks, I'd try [this version](https://www.npmjs.com/package/patternengine-node-nunjucks) and see if it works. The primary pattern-lab dev has said that v3 makes extensive use of promises whereas v2 is largely synchronous.

**Comment by ivandoric** [comment]
Oh, ok. I will try that. Thanks.

**Comment by ivandoric** [comment]
Installing the nunjucks engine version 0.1.2 did the trick. Thanks @Josh68

**Comment by Josh68** [comment]
Good to hear I actually gave some valuable advice ;)
