### ISSUE TITLE
CSS not loaded in the page nor public/index.html

### ISSUE THREAD

**Issue by nicoguefveneu** [Comcast/patternlab-edition-node-webpack#2]
Hello,

I've been testing your tool with a simple atom button, and so far, the CSS isn't reflected in the page, whereas it is loaded with webpack :
 css/button.css   25 bytes          [emitted]

I have :
\source\_patterns\01-atoms\buttons
 - button.mustache
`<button type="submit" class="btn">
	Search
</button>
`
 - button.md
`---
title: Primary Button
---

Primary button.
`
This works well in the page

and :
\source\css
- button.css

But then this CSS is loaded with webpack but not loaded in the page.
I also tried to put other CSS (even a minified CSS file here), and again the CSS is loaded in the webpack console but not loaded in the page.

In addition, when I go to the public folder, the CSS file is in the CSS folder, but no link to it in the index.html.

Am I missing something ? a configuration ?

Thanks !

ps: I also tried the Pattern Lab/Node: Gulp Edition and same problem.

**Comment by nicoguefveneu** [comment]
Sorry for the issue, I finally found, I guess, the answer:
http://patternlab.io/docs/pattern-header-footer.html

Because CSS were loaded automatically, I thought I have not to declare them !

**Comment by mbulfair** [comment]
@nicoguefveneu I'm glad you found a solution, let me know if I can help in anyway.

**Comment by nicoguefveneu** [comment]
@mbulfair well just let me know if adding the link to my CSS files in the _00-head.mustache is the right thing to do ?

**Comment by mbulfair** [comment]
Yes you can place a reference to a css file in the head mustache file, the copy function moves all .css files under source/css to public/css

**Comment by nicoguefveneu** [comment]
Ok !
Cheers !
