### ISSUE TITLE
ES2015 Preset error

### ISSUE THREAD

**Issue by jenter** [Comcast/patternlab-edition-node-webpack#20]
## I found the following issue:
After completing the install instructions, I receive the following errors when running `npm run patternlab:serve` for each of the JS files in "./source/js/*"
```
ERROR in ./source/js/progress.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "[DIR]/source/js"
```

### Recommendations on Solutions:
This can be fixed by running `npm install babel-preset-es2015`. 
Suggestion would be to include the `babel-preset-es2015` in the `package.json` file to avoid this manual step.

**Comment by mbulfair** [comment]
@jenter Which branch did you use? I removed this from latest, but only master has the official release. If I made a mistake i'll quickly go back and fix it.

**Comment by mbulfair** [comment]
I just pushed https://github.com/Comcast/patternlab-edition-node-webpack/releases/tag/v1.0.6 which should resolve this issue.

**Comment by jenter** [comment]
@mbulfair I was pulling from master. I will reference that release then and thanks for the update.
