### ISSUE TITLE
Having trouble getting SCSS to compile

### ISSUE THREAD

**Issue by Flowgram** [Comcast/patternlab-edition-node-webpack#32]
Hi, 

I'm using:

Using Edition Node Webpack : v2.0.0
Node: v8.9.0
npm: v6.4.0

As directed, I copied the sample webpack.app.scss.js to the _app folder.

I've installed all these node packages:

`npm install postcss-flexbugs-fixes mini-css-extract-plugin path style-loader css-loader postcss-loader sass-loader import-glob-loader node-sass autoprefixer`

`npm run patternlab:serve` runs without error and something seems to happen when I make changes to scss files in /source/public/css/scss/ but nothing gets compiled.

I'm sure this is down to my lack of Webpack knowledge, but what else do I need to do? How does js/sample-project fit into this? 

Also might be worth mentioning that after installing all the npm packages the live reload of my css and twig files stopped working.

Many thanks for any help or pointers.

**Comment by davidlagace** [comment]
@Flowgram Same problem here... :/

What I did..
1.  Follow the install process from the step by step .readme (Cloned the repository, npm install,etc.)
2.  Replaced the content of the _**/source/samples/webpack.app.js**_ by the _**/source/samples/scss/webpack.app.js**_ file. 
3. Changed something in the _**\source\css\style.scss**_ file
4. Lunch `npm patternlab:serve`
5. Nothing happen, my CSS file was the same

Then I tried compiled the prod version ( `npm run patternlab:build` )

And yayy I got an error that tells me that something is wrong with the entry by I'm not a pro at webpack. Can Someone please help ! :)

Here's the error log 
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry['js/sample-project'] should be a string.
      -> The string is resolved to a module which is loaded upon startup.
    * configuration.entry['js/sample-project'] should not be empty.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
```

**Comment by ItsJepser** [comment]
Same problem here, nothing will change when I edit the scss files... ;(

**Comment by mbulfair** [comment]
@davidlagace The error looks like the entry is incorrect. Looks to still be pointing to `['js/sample-project']` this should be your own entry, and to keep it simple you should just make it 1 file. Post the entry you have.

**Comment by ItsJepser** [comment]
Hello @mbulfair ,

The page says, its easy to import SCSS files with the sample given, me and my collegue have worked 2 days on this, but we didn't manage to find out how this works, is there any chance you could give an explaination on how to set this up?

**Comment by mbulfair** [comment]
@ItsJepser Can you share with me on gitter that would be the best way to help.

**Comment by rspauwen** [comment]
@mbulfair, me and @ItsJepser concluded (finally) that in our case the `starterkit-mustache-demo` was causing the build process not to include any SCSS changes since it also modifies `_01-foot.mustache`. 

So, to anyone whose having the same issue: after installing a PatternLab starterskit, you need to make sure that the bundles (i.e. `js/pl-source`, or a different name for the scss bundle) are included properly in the footer. Hope this clarification is helpful for someone!

**Comment by mbulfair** [comment]
That's great to hear.
