### ISSUE TITLE
After insert webpack sample file js don´t compile anymore

### ISSUE THREAD

**Issue by thrsh** [Comcast/patternlab-edition-node-webpack#38]
## I have the following issue:

I installed the project like it´s described in the readme. 
'npm install starterkit-mustache-demo'
'npm run patternlab:loadstarterkit --kit=starterkit-mustache-demo'

Then I replaced the _app/webpack.app.js file with  _app/samples/scss/webpack.app.js
and added the dependencies with running:

`npm install autoprefixer import-glob-loader css-loader node-sass postcss-loader postcss-flexbugs-fixes mini-css-extract-plugin sass-loader style-loader --save-dev`

After that, I changed the paths in _01-foot.mustache to:

{{{ patternLabFoot }}}

  <script src="../../js/pl-source-vendor.js?{{cacheBuster}}"></script>
  <script src="../../js/pl-source.js?{{cacheBuster}}"></script></body></html>

--

Now I have the problem, that my JS and my SCSS files are not compiled. I also tried to change the path to sample-project.js but nothing happens. 

When I run 'npm run patternlab:build' I get this error message in my terminal:**

_Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    * configuration.entry['js/pl-source'] should be a string.
      -> The string is resolved to a module which is loaded upon startup.
    * configuration.entry['js/pl-source'] should not be empty.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]_

I think there is something wrong with the sample file or the webpack merge, but I can´t find the error by my own. 
I would be very grateful if someone can help me!

**Comment by mbulfair** [comment]
@thrsh this basically boils down to there are no file in the entry. If you're using the merge make sure you've defined the new files so the merge uses yours over the default. It just needs atleast 1 .js file.

**Comment by thrsh** [comment]
Hey @mbulfair, do you mean a entry weback file for merging with webpack.config.babel.js? Where can I define that? thanks!

**Comment by mbulfair** [comment]
It means there are no files https://github.com/Comcast/patternlab-edition-node-webpack/blob/latest/source/_app/samples/scss/webpack.app.js#L25 in this folder. This scans for any file in those folders. If you have 0, it will break. just add a `index.js` as a test in that folder and it should build.

**Comment by thrsh** [comment]
hmm but the starterkit generated several files in this folder:
source/js/

**Comment by mbulfair** [comment]
If you edit the file to be that folder again, `source.js` vs `source.patterns` see if that works.

**Comment by thrsh** [comment]
yeah now the js files compile :) thank you!
one problem is solved. I thought when the JS finally works, the scss files will compile, too .... 

My entry looks like that now:
entry: {
            "js/pl-source": globby.sync(
                [
                    resolve(`${plConfig.paths.source.css}scss/*.scss`),
                    resolve(`${plConfig.paths.source.patterns}**/*.js`),
                    resolve(`${plConfig.paths.source.js}**/*.js`),
                    "!**/*.test.js"
                ],
                {
                    gitignore: true
                }
            )
        },

the style.scss is in the css folder and all other scss files are in different subfolders in css/scss/subfolder 

Any Idea?

**Comment by thrsh** [comment]
@mbulfair  is there any chance to get help via gitter?

**Comment by thrsh** [comment]
We figured out, that you should downgrade css loader to 1.0.1 and if somebody use the starterkit files, you should put your style.scss into source/css/scss/
