### ISSUE TITLE
Do not install obsolete files when install via npm

### ISSUE THREAD

**Issue by renestalder** [Comcast/patternlab-edition-node-webpack#6]
## I found the following issue:

When edition-node-webpack is installed via npm, it also installs the full source folder. As I understand, to use edition-node-webpack as dependency, you would add your own npm scrupts to your package.json, that `cd` to the `node_modules/edition-node-webpack` folder and run the individual commands.

### Recommendations on Solutions:

Ignore obsolete folders like `source` or parts of `source` when using edition-node-webpack as dependency.

Feedback welcome if I see or use this wrong.

**Comment by mbulfair** [comment]
@renestalder While what you are saying is valid, and you would have to write extra scripts to access the library as a dependency, I am following the same direction as the other 2 editions. Version 3.x of the core library will make these editions easier to access and at that time I will make any changes that improve workflow and performance. 

Thanks for the feedback 👍
