### ISSUE TITLE
JS doesn't fire when opening a 'page' in a new window

### ISSUE THREAD

**Issue by jephjohnson** [Comcast/patternlab-edition-node-webpack#7]
## I found the following issue:

I am hosting the 'public' folder on a server and all is working fine. 

However, when I click the "open in a new window" link in the drop down and It opens in a new window. My JS doesn't fire. In my console I am seeing '. This happens locally as well.

```
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
```

How do I view my project working as expected outside of the patternlab enviorment?

**Comment by mbulfair** [comment]
@jephjohnson Sorry for the late reply. Typically for things like CSS you include the .css files first, then the .js bundle that outputs the css for the live reloading. In the footer you link your output bundles. When webpack runs in production, it just outputs the bundles to your public destination, As long as those are linked in the head/foot it will work correctly.

_head.mustache
```
<link rel="stylesheet" href="../../css/bundle-first.css?{{ cacheBuster }}" media="all" />
 <!-- Webpack Hot Reload -->
 <script src="../../css/bundle-first.js"></script>
```

**Comment by jephjohnson** [comment]
@mbulfair - Thank Matt, I ended up getting it sorted

**Comment by mbulfair** [comment]
Looks like Brian replied to that issue, if you find anything else, please don't hesitate to log a issue on either or both projects.
