### ISSUE TITLE
17 seconds to compile all mustache files

### ISSUE THREAD

**Issue by soelen** [Comcast/patternlab-edition-node-webpack#8]
For the sake of how fast patternlab-edition-node-webpack is going to compile huge projects I inserted around 400 simple to complex template files. As the title of this issue reveals it takes about 17 seconds to go trough all files.

Is there a way to shorten the compile time?

**Comment by mbulfair** [comment]
Hello @soelen the 1st build may take some time to compile the 400 templates. However the next run should be faster. 

Have you set this to `false`
https://github.com/Comcast/patternlab-edition-node-webpack/blob/latest/patternlab-config.json#L40

**Comment by soelen** [comment]
Thanks @mbulfair, that did the trick 👍
