### ISSUE TITLE
Error: missing script: patternlab:build

### ISSUE THREAD

**Issue by samsmithnz** [Comcast/patternlab-edition-node-webpack#9]
## Error: missing script: patternlab:build
Hi, hopefully this is the right place for this - if it's not, please delete/ redirect me to the correct location. I'm having a few challenges setting this up, with the following error after I type "npm run patternlab:build". I've downloaded the latest release source code (https://github.com/Comcast/patternlab-edition-node-webpack/releases/tag/v1.0.5), What have I done wrong? Any tips on how to debug this? This is right up against the edge of my Node/NPM knowledge.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'patternlab:build' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose stack Error: missing script: patternlab:build
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
5 verbose cwd D:\_work\2\s
6 verbose Windows_NT 10.0.14393
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "patternlab:build"
8 verbose node v9.5.0
9 verbose npm  v5.6.0
10 error missing script: patternlab:build
11 verbose exit [ 1, true ]

```

Thanks!

### Recommendations on Solutions:
TBD

**Comment by mbulfair** [comment]
Are all of the scripts not working? Or just this one? 
1. Make sure you `CD` into the directory in which you cloned this project
2. Run `npm install`
3. Run `npm run patternlab:serve` or `npm run patternlab:build` to just get it to compile

**Comment by samsmithnz** [comment]
Hi, when I run those commands, (see screenshot below), it outputs the message above (with two warnings, that I think are ok...?). 
![image](https://user-images.githubusercontent.com/8389039/36154625-079044c0-10a0-11e8-846f-b453d8c5292b.png)

**Comment by samsmithnz** [comment]
I think I'm getting closer to figuring this out - it's a problem with the .gitignore file. To replicate, copy the source to a new repo, push it, and then download it to a fresh machine - the .gitignore file seems to be filtering out some files (need to identify these still), which the fresh machine can't find/ build.

**Comment by mbulfair** [comment]
`.gitignore` is only really blocking node_modules and public. All you need is to make sure your `package.json` matches what is in the branch.

![image](https://user-images.githubusercontent.com/5325543/36156622-a44d5fdc-10a5-11e8-8741-e0e6db0a18b9.png)

I notice I have legacy yarn in there, so I need to change that. 

Here's my output of latest of master.

![image](https://user-images.githubusercontent.com/5325543/36156520-429b07da-10a5-11e8-8933-3351f0fc781f.png)

Also I'm running `NPM 5.6.0 and Node 8.9.4 `

Since you are on windows I would suggest installing [NVM ](https://github.com/coreybutler/nvm-windows#node-version-manager-nvm-for-windows)

Lastly I am not using powershell, but that shouldn't really matter.

**Comment by samsmithnz** [comment]
Thanks, this was really helpful and this can be closed / deleted. I had a cross over of source and gitignores. It was the non-descript error that was throwing me off, but I've got it working now (you are right that it works in both PowerShell and Cmd)

**Comment by mbulfair** [comment]
That's good news, I personally use the git bash with visual studio code. Hate having too many windows open. Hope you like this edition, I am really trying to get it update with the 3.0 release of core.
